### PR TITLE
Document sunsetting policy for Node 12

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
This PR documents our intention to support our enterprise customers. As part of a "Pulumi EOL" issue, I did some reading to determine what kind of policies we can publish around version support -- in the case of this repo, only Node support is required to disclose, since yarn, typescript, etc are all build-time dependencies.

It also provides a public announcement of our intention to end support for Node 12 in December.

Closes https://github.com/pulumi/actions/issues/707

### CODE REVIEW

**Comment by cobraz** [comment]
Could we do a major bump and start running node v16 today?

**Comment by RobbieMcKinstry** [comment]
Hmm, that's a good point! I think that's preferred over continuing to support Node 12, since it has been sunset.

**Comment by RobbieMcKinstry** [comment]
I asked around internally, and here's a summary of the conversation:

One person expressed concern that users who don't specify a version of the action will get automatically upgraded to `v4` and will still experience the breaking change. I feel that comes with the territory of not pinning a major version...

Someone else suggested we cut a release `@v3-nodejs12` and tell customers to pin to that if they need Node 12, then continue to release on the `v3` line. That requires coordination with the customers since we'd have to communicate to our CX engineers that users need to pin to that version. Then, we'd have to give them some time to implement the change before we cut the new release. I presume it would also be preferable for us to communicate a v4 release before it happens. 🤷🏻‍♂️

I noted that if we're going to be blocked until users make the pinning change, we might as well wait until December anyway, at which point GH Enterprise v3.3 will have been deprecated, and we can upgrade without issue. Those in the discussion agreed that we should broadcast the expected change now (via a pinned GH Issue and documentation in the README). So the conclusion was essentially to merge this PR and pin an issue to the top of the backlog to prepare users for the migration. 😕

**Comment by t0yv0** [comment]
If this helps, for context https://github.com/pulumi/actions/pull/651 - we can request feedback from Stanislav if we go that route. There might be more users affected but that's the one user we definitely heard from before when upgrading to 16.

**Review by t0yv0 — APPROVED** [review]
Decided to accept as is for the moment. Please let me know if any features are blocked on the upgrade.

**Pull request merged**
