### PR TITLE
feat: update action runtime to NodeJS 16

### PR DESCRIPTION
**Pull request by ahanoff**
Close https://github.com/pulumi/actions/issues/752

> As a result, actions authors who move from targeting Node.js 12 to Node.js 16 should release with a new major version number to communicate that there is a possible breaking change for GitHub Enterprise Server 3.3 and earlier.

https://github.blog/changelog/2022-05-20-actions-can-now-run-in-a-node-js-16-runtime/ - Github recommends to update major version of action if runtime changes.

Let me know if you would like to keep v3, then I'll revert it back

### CODE REVIEW

**Comment by RobbieMcKinstry** [comment]
Thanks for this PR @ahanoff . We won't be able to merge until December for the reasons stated in the linked issue, but we'll revisit this PR at that time. 👍🏻  It's very nice to have a PR ready-and-waiting to merge for when the upstream becomes unblocked! :)

**Review by RobbieMcKinstry — CHANGES_REQUESTED** [review]
Awaiting 07 December 2022 as per https://github.com/pulumi/actions/issues/752

**Comment by RobbieMcKinstry** [comment]
GH has delayed the deprecation of GHE v3.3 until 18 Jan 2023. As a result, that's the new "do not merge until" date for this PR. :(

**Comment by dotansimha** [comment]
@RobbieMcKinstry can you please elaborate on the need to wait for that specific date? what's preventing us from updating to node16 or node18 and shipping a new version that uses an up-to-date node version right now?

**Comment by RobbieMcKinstry** [comment]
Hi @dotansimha https://github.com/pulumi/actions/issues/752 has a more detailed write-up.
Technically, there's nothing stopping us from cutting a new major release right now.

**Comment by ahanoff** [comment]
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

**Comment by RobbieMcKinstry** [comment]
@ahanoff, I've rebased this branch off of master, and I'm making a few other tweaks so we can get this in 👍🏻

**Review by RobbieMcKinstry — APPROVED** [review]

**Pull request merged**
