### PR TITLE
feat: comment on GitHub step summary

### PR DESCRIPTION
**Pull request by koozz**
Using the [GitHub step summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) feature, the Pulumi output can be stored on the GitHub step. This defeats the need to dive into the individual steps and find the Pulumi output.

The input parameter `comment-on-summary` has the non-breaking default `false`. If `true`, then the action will add the results of the Pulumi action to the GitHub step summary.

Have tested it by referencing fork:

```yaml
  - uses: koozz/pulumi-actions@e399df46ff12c78394bba8dbb593c13bacf9b844
    with:
      comment-on-summary: true
      # ...
```

Showing the output in the Job summary:

image

Fixes: #761

### CODE REVIEW

**Review by ma-ts — APPROVED** [review]

**Review by simenandre — APPROVED** [review]

**Comment by simenandre** [comment]
@koozz Would you mind removing the dist files update so we can run the workflow tests on this change? :)

It's a bit weird how this goes, but we optimized it so that changes that did nothing to our dist files were skipped. Which I at least think is why they are not triggered 😅

**Comment by koozz** [comment]
> @koozz Would you mind removing the dist files update so we can run the workflow tests on this change? :)
> 
> It's a bit weird how this goes, but we optimized it so that changes that did nothing to our dist files were skipped. Which I at least think is why they are not triggered 😅

Sure one sec.

**Comment by koozz** [comment]
@simenandre I just disabled the workflows on my fork and dropped the automated commit from the PR.

**Comment by koozz** [comment]
Hi @justinvp, please tag me if I need to change something else.

**Comment by ma-ts** [comment]
Wow! Amazing feature. Would love to see this merged.

**Comment by koozz** [comment]
Hi @simenandre,

you added @justinvp but maybe there's someone else who can review and merge it?

Kind regards and let me know if an update is required,
Jan

**Review by justinvp — APPROVED** [review]
LGTM. Thanks for your patience!

**Pull request merged**
