### PR TITLE
feat: Support colorized output

### LINKED ISSUE #84: Output is not colorized
GitHub Actions supports colorization, so it would be awesome if it would take the colors of the CLI output and show it correctly.

The colors create less confusion, and make it easier to see what will be added, deleted and replaced.

### PR DESCRIPTION
**Pull request by sqdk**
Adds support for configuring colorized output.

I am unsure what exactly is required for contributing to this repo. Please let me know if something more is needed.

Fixes #84

### CODE REVIEW

**Comment by sqdk** [comment]
To whomever allowed the CI suite to run yesterday: I fixed the tests :) Not sure about the issue with the macos tests. Seems like something i cannot fix.

**Comment by cobraz** [comment]
@sqdk Can you rebase, it should fix the macos issues :)

**Comment by sqdk** [comment]
@cobraz Done :)

**Comment by RobbieMcKinstry** [comment]
Hi @sqdk,
Thank you for your contribution! Would you mind adding a description of this option to the README as part of your pull request? :D

**Comment by sqdk** [comment]
@RobbieMcKinstry Aaaand done :)

**Review by cobraz — APPROVED** [review]

**Review by RobbieMcKinstry — APPROVED** [review]

**Comment by RobbieMcKinstry** [comment]
Thanks very much for your contribution @sqdk! I'm always so excited to see color added to the terminal! I find it always makes for a great user experience. :)

**Comment by DeanShackleyNewDay** [comment]
Hey, when we try and use this after version version v3.17.0 we get no output logged via github actions workflow.  We have tried to set the color option to always, never, and raw but no difference.  We just seem to get empty lines.  It seems like only the up command is affected as our previews have logs.  If we tag version v.3.17.0 we see logs.  Can you advise please?

**Comment by RobbieMcKinstry** [comment]
Hi @DeanShackleyNewDay we're tracking this issue as #731. Some users have pinned to v3.17.0 as a workaround for now.
What makes you think the bug you're experiencing is coming from this issue? (I haven't found the source of #731 yet so I'm curious; you might have a lead for me. 😄)

**Pull request merged**
