### PR TITLE
feat: Add `configMap` option

### PR DESCRIPTION
**Pull request by Moon1706**
Hi! I've added the field `configMap` for the configuration of stack. The MR can close [this issue](https://github.com/pulumi/actions/issues/165). I newer in Typescript, so if you have suggestion who improve my code, please ping me.

### CODE REVIEW

**Comment by cobraz** [comment]
Thanks! This is a very nice addition. How do YAML working like this? Do you have an example?
Maybe you want to add a test for it amongst our Github Actions workflows?

If you haven't already, we should probably do some research what the best approach to provide a configMap object like this.

**Comment by Moon1706** [comment]
@cobraz 
Example: [action](https://github.com/Moon1706/pulumi-action/blob/main/.github/workflows/default.yml) and [README](https://github.com/Moon1706/actions/blob/master/README.md?plain=1#L95).
Testing is a tough question. I wanted to add type testing of `configMap` field in [this string](https://github.com/Moon1706/actions/blob/master/src/config.ts#L40), but I don't pretty good understand who in TS work system of types, because if I tried to insert in [mention string](https://github.com/Moon1706/actions/blob/master/src/config.ts#L40) type `ConfigMap` from the import package I got error(

**Comment by terraform-gitlab-modules** [comment]
PS. Of course, if you need to research this, I'll give you all information that I have.

**Comment by Moon1706** [comment]
PS. Of course, if you need to research this, I'll give you all information that I have.

**Comment by cobraz** [comment]
> @cobraz 
> 
> Example: [action](https://github.com/Moon1706/pulumi-action/blob/main/.github/workflows/default.yml) and [README](https://github.com/Moon1706/actions/blob/master/README.md?plain=1#L95).
> 
> Testing is a tough question. I wanted to add type testing of `configMap` field in [this string](https://github.com/Moon1706/actions/blob/master/src/config.ts#L40), but I don't pretty good understand who in TS work system of types, because if I tried to insert in [mention string](https://github.com/Moon1706/actions/blob/master/src/config.ts#L40) type `ConfigMap` from the import package I got error(

Thanks!

I was thinking to add configMap option to .github/workflows, not necessarily a unit test.

**Comment by Moon1706** [comment]
Mmm, so do you mean move a chunk of testing (for example, `configMap`) to .github/workflows? Do I right understand you?

**Comment by cobraz** [comment]
Yeah, you can see an example here: https://github.com/pulumi/actions/blob/34eedc3989fcde2b45e9d11246992a5fea6c50f1/.github/workflows/workflow.yml#L90-L122

**Comment by Moon1706** [comment]
Hm, Okay, I seem to understand what you mean. I'll check my ideas and get back to you, ok?

**Comment by Moon1706** [comment]
@cobraz Check please

**Comment by Moon1706** [comment]
@cobraz ping

**Comment by cobraz** [comment]
@Moon1706 Could you remove the dist files? :)

**Comment by Moon1706** [comment]
@cobraz  Done

**Comment by Moon1706** [comment]
@cobraz 
Mmm, does my PR have any problem or it will be added soon?

**Comment by Moon1706** [comment]
@mikhailshilkov Hi! Could you review my PR?

**Comment by Frassle** [comment]
> @Moon1706 Could you remove the dist files? :)

I think they need recompiling not removing. This PR is currently at -88000 lines!

**Comment by stack72** [comment]
He meant remove them from your PR - dist files should not be part of a PR :)

**Comment by Moon1706** [comment]
Okay. First time I re-compiled the code. @cobraz told me delete `dist` directory. Then @Frassle said get back the code. Then @stack72 said `dist` files should not be part of a PR. Besides, if I right understand workflow not make sense, added I this directory or not, because after `push` workflow actions rebuild this folder.
So, what do you want?

**Comment by Moon1706** [comment]
It won't work, but I'll try to fix it

**Comment by Moon1706** [comment]
@Frassle 
I've fixed it. Please check CHANGELOG. I've deleted version 3.16, because pulumi-action doesn't have this version.

**Comment by Moon1706** [comment]
And keep in the head that if any changes merge to the master this PR will be unrelevant.

**Comment by Frassle** [comment]
hmm build seems sad about something, will take a look when I've got some time.

**Comment by Moon1706** [comment]
@Frassle 
I'm really sorry. I investigated these problems.
Firstly, I found yaml packages trouble and [notify official repo](https://github.com/eemeli/yaml/issues/397) about this. Now, I figure out with another strange behavior. I'll ping you when solve it.

**Comment by Moon1706** [comment]
@cobraz 
@Frassle 
@stack72 
Hey, do you know your tests probably don't work? If I right understand they last time worked with version 3.33.2. 
Check please the destroy step of 'Actions Workflow'.

**Comment by eemeli** [comment]
Noting also here what I commented on eemeli/yaml#397:
> This is not a problem with `yaml`, but with other tools that need to be updated.
>
> In this particular case, it looks like `@pulumi/pulumi` is using `typescript@3.7.5`, which does not support optional chaining (the syntax with which you encountered this error). You should get that updated to at least v3.8, which was released two years ago.

**Comment by Moon1706** [comment]
@Frassle 
Could you help me with this case https://github.com/Moon1706/actions/actions/runs/2475880988 ?

**Comment by Moon1706** [comment]
@Frassle 
@cobraz
@stack72 
Hey, you know that windows-latest have already had pulumi utility without using pulumi-setup? And when you realized your tests, you used a build-in version of pulumi instead of version pulumi from GitHub action. Windows-latest destroy command will end with error, because pulumi version 3.34.0 has memory error.

**Comment by Moon1706** [comment]
Error with yaml package I've fixed a moving execution code from node12 to node16. Node14 isn't build-in in GitHub runners.

**Comment by cobraz** [comment]
> Hey, you know that windows-latest have already had pulumi utility without using pulumi-setup? 

Yes, but we didn't always. Our workflow tests haven't been updated after that was added, it's on my list 👍

**Comment by Moon1706** [comment]
Okay. So, I suggest waiting a week, because in official documentation GitHub runners are information that software [update weekly](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software).

**Comment by cobraz** [comment]
> Okay. So, I suggest waiting a week, because in official documentation GitHub runners are information that software [update weekly](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software).

We're [deleting the installed Pulumi](https://github.com/pulumi/actions/blob/5714940e68d4c73339511ac122dac86eb8443231/src/libs/pulumi-cli.ts#L50-L55) in our script. It might be that we're not doing that correctly for the one already installed in the Github Actions runner. However, there shouldn't be a dependency on the already installed one. I've created a pull request (#644) that removes all the `setup-pulumi` steps, since they shouldn't be needed.

**Comment by cobraz** [comment]
I confirmed that we're indeed deleting the already installed Pulumi CLI: https://github.com/cobraz-sandbox/which-pulumi/runs/6843143850

**Comment by cobraz** [comment]
@Moon1706 I've opened a small fixup for your PR in #645, just removed unrelated changes so it's ready to close :)

If you'd like, you can merge that with this PR (or we can wait for a review on mine).

**Comment by Moon1706** [comment]
@cobraz I've added the comment to [your PR](https://github.com/pulumi/actions/pull/645). Check please and, yea, you can close my PR.

**Comment by nicholasgibson2** [comment]
@cobraz Do you have a separate pull request for the `downsert` feature this pull request was also going to add?

**Comment by Moon1706** [comment]
@nicholasgibson2 
I guess no and I doubt that it'll happend. As I've mentioned, additional functionality really slooooowly appended to this Action. I try to add configMap 2 month. So, for this reason, I've stared to develop new features in [my own Action](https://github.com/terraform-gitlab-modules/actions), based on this code.
@cobraz 
What do you think about creation unstable vesrions of this Action? Just for rapid develop.

**Pull request closed without merging**
