### PR TITLE
(WIP) Javascript-based Pulumi Github Action

### PR DESCRIPTION
**Pull request by cobraz**
Hello 👋

After a nice chat with @chrsmith yesterday, I started doing some initial testing of a Typescript/Javascript-based Github Action. Intentions are to make the Pulumi Github Action quicker and to follow [Github guidelines](https://help.github.com/en/actions/building-actions/about-actions#choosing-a-location-for-your-action), eventually publish according to [Github documentation](https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace) to make it discoverable at [the Markedplace](https://github.com/marketplace?type=actions&query=pulumi).

This WIP pull request is meant to check in with the Pulumi team to see if this is the direction to take.

#### TODO

- [x] Fix issue where `node` is not found ([Failing workflow](https://github.com/cobraz/pulumi-action-2.0/runs/931555852))
- [ ] Add tests
- [ ] Add PULUMI_CI_* environment variables
- [ ] Add `.pulumi/ci.json` configuration
- [ ] Add stack name input variable
- [ ] Add updated documentation
- [ ] Add PR comment functionality

Testing repository: https://github.com/cobraz/pulumi-action-2.0

cc: @chrsmith @praneetloke 

Fixes pulumi/pulumi#4660

### CODE REVIEW

**Comment by stack72** [comment]
This is fantastic @cobraz 

I know that @jaxxstorm will be very interested in this!

**Comment by cobraz** [comment]
I've done some quick research as to why `node` is not found. Started to do [some tests](https://github.com/cobraz/go-test-lookpath/runs/931689256) to see if `exec.LookPath("node")` at `pulumi-language-nodejs/main.go` could be the problem. That didn't result in anything useful, so I'm thinking it could be the [environment variables we are setting](https://github.com/cobraz/actions/blob/4d9f7d5ace21c7034f72fd1953ec95e963d1d820/src/main.ts#L101). Maybe adding `env` to `exec.exec()` removes all other environment variables, or we actually have to set the variables to expose them. I'll try more later today :)

Would be cool to have a _working-copy_ before I leave it for a decision is made :)

**Comment by cobraz** [comment]
Btw, an idea could be to expose pulumi outputs as well. Guess there are more than a few that would appreciate that :)

**Comment by cobraz** [comment]
Great news, [this recent build](https://github.com/cobraz/pulumi-action-2.0/runs/932179285) deployed `hello-aws-javascript` in 1 minute and 7 seconds (35 seconds on the actual Pulumi step). 🎉

**Comment by cobraz** [comment]
Is there any news about this? :)

**Comment by chrsmith** [comment]
Thank you for the pull request, as well as your patience in us getting back to you! There is a lot of stuff going on here, so let me try to brain dump my understanding of things:

## Current State of the World

Here is a quick recap of the current state of the world, and background for what this PR is trying to achieve:

### Pulumi has an “official” story for GitHub Actions

Pulumi currently publishes/maintains a Docker container that you can use with GitHub Actions, which contains language runtimes you would need.

https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/

It works well enough, but has a few drawbacks:

- A lot of logic is baked into the [entry point script](https://github.com/pulumi/pulumi/blob/master/docker/actions/entrypoint.sh), such as running `gcloud auth activate-service-account` or even leaving comments on the source GitHub pull request!
- Since it contains the language runtimes (e.g. Golang, Python, .NET runtimes) the container itself is very large.
- Since it uses Docker, so it isn’t as portable/easy-to-use as GitHub Actions that are packaged as JavaScript.

So by publishing a JavaScript-based “GitHub Action” for Pulumi, we can make the experience smoother in a few ways. Most notably, that it will be faster to run. But users will be on their own with regard to installing language runtimes. (Instead, using actions like https://github.com/actions/setup-dotnet.)

### Pulumi has a GitHub App for commenting on PRs

One of the big values in running Pulumi on a GitHub action is so you can run `pulumi preview` for pull requests. So you can see if a code change will make any unexpected infrastructure updates.

This was precisely why we built the Pulumi “GitHub App” back in the day, well before GitHub Actions were a thing.
https://github.com/apps/pulumi

While our current GitHub Actions container supports leaving comments on PRs, the GitHub App can do a better job. As it routes through https://app.pulumi.com, so we can do a better job formatting the comment and/or referencing other data that isn’t directly emitted from the `pulumi` CLI.

This isn’t a major issue, but does mean that the story for using Pulumi with GitHub is a bit more confusing. i.e. should we deprecate the Pulumi GitHub Action in favor of just doing PR commenting via GitHub Actions? (But what about people on GitHub who _aren’t_ using GitHub Actions for CI?)

### What is the Scope Anyways?

Having a basic `pulumi/actions` action simply download/install Pulumi if needed and run `pulumi <args>` probably isn't sufficient. To actually achieve continuous delivery, you'd need to have your GitHub Actions workflow run `pulumi preview` on pull requests, `pulumi up` on commits. And depending on the branch make, either select a `testing` or `production` stack... kind of a mess.

So we've long discussed putting all of that configuration data in a file like `.github/pulumi/ci.json`, which a GitHub Action could then pull from and know what to do.

But from a design perspective, that would take a lot of thinking to get right.

## Next Steps

Taking that all into consideration, and looking at your PR, it seems like this is on the right track. Here’s what I would propose as the next few steps to keep the ball rolling here:

### 1.) Resubmit this PR to the new `v2-dev` branch

If you don't mind, let's keep iterating on the code in your PR so we can get that checked-in and start doing some better testing.

We certainly aren't ready to blow away the `master` branch of this repository just yet. But @cobraz, would you mind resubmitting this PR to merge it into the new `v2-dev` branch of this repo (https://github.com/pulumi/actions/tree/v2-dev)?
That would allow us to make make progress until we're ready to ship a complete-enough v1 of a JavaScript-based GitHub Action.

I'll have a bunch of nit picks and things for you, but the biggest thing would be making sure the new TypeScript code matches the rest of Pulumi's codebase. Essentially if you hook up [this tslint.json file](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tslint.json), it should point out any problems.

Also, it would be great to have some sort of test coverage for this if it isn't too difficult to add. Taking a quick peek at other actions in the https://github.com/actions organization, the approach the [heroku action](https://github.com/actions/heroku) took might be easy to replicate ([ex](https://github.com/actions/heroku/blob/main/script/test), [ex](https://github.com/actions/heroku/blob/main/test/bin/heroku)).

But since this PR has been collecting dust for so long, I'm happy to err on the side of getting this in and making progress than trying to make the very first commit perfect.

### 2.) Let me bug some Pulumi folk

I’ll set up a meeting with @praneetloke and @jaxxstorm to confirm our tentative roadmap/plans here.

- Are we really sure that Pulumi should sign up for shipping/maintaining _another_ way to integrate with GitHub?
- Would this work well with other features in the pipeline related to CI/CD, as well as other integrations we have for GitLab, Azure Pipelines, etc.
- What is the exact scope of what we would want to do for a v1 of a JavaScript-based GitHub Action? (Which most likely would just be the "download/install pulumi; run CLI with args" and leave PR commenting and `ci.json` for a v2, by which time hopefully we'll have a better understanding of what sorts of requirements / configuration knobs we'd need.)

Thank you again for your patience @cobraz , we do appreciate the contribution. Does that all sound like a reasonable plan?

**Comment by cobraz** [comment]
Yes!

I think it all sounds great. Certainly, I can resubmit the pull request. I'd like to contribute much more than what I've done so far. I'd gladly tag in to any meeting about this, if you'd like.

I see this as great way to learning in many ways. It also benefits me in many ways (having to maintain so many smaller repositories with Pulumi code)

As we discussed earlier on Slack, I threw something together to MVP the thing. Adding all the commands and configuration for this to actually work in the real world is the intention. Testing is important too, so yes :)

**Comment by chrsmith** [comment]
Cool. Let's close this out then, and I'll work with you on a new PR to put this into a feature branch.

**Pull request closed without merging**
